blank_issues_enabled: false
contact_links:
  - name: CurseForge project page
    url: https://www.curseforge.com/minecraft/modpacks/inventors
    about: Download the latest release and check for known beta files.
