#Y level where surface contraptions transfer to orbit
# Default: 512.0
# Range: -2048.0 ~ 100000.0
ascendThreshold = 256.0
#Y clearance from the opposite transit boundary after dimension transfer
# Default: 16.0
# Range: 0.0 ~ 100000.0
transitionOffset = 16.0
#Whether to log the dirt block on common setup
logDirtBlock = true
#A magic number
# Default: 42
# Range: > 0
magicNumber = 42
#What you want the introduction message to be for the magic number
magicNumberIntroduction = "The magic number is... "
#A list of items to log on common setup.
items = ["minecraft:iron_ingot"]
